### ISSUE TITLE
Use a license more suited to code

### ISSUE THREAD

**Issue by Calinou** [ShiftyAxel/Qodot#17]
I noticed this repository is under the [CC BY 4.0 license](https://github.com/ShiftyAxel/Qodot/blob/master/LICENSE). Since [Creative Commons licenses aren't recommended for software](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software), what do you think about using a license like MIT instead?

**Comment by ShiftyAxel** [comment]
@Calinou I'm open to the idea of switching to MIT, since almost every other tool in the asset library seems to use it and I want to minimize the amount of barriers between devs and being able to use Qodot.

CC BY has been my casual go-to for years because I'd prefer to be credited if my work is used, and my casual glance-read of MIT makes it look like only the license itself is necessary. Can you offer any insight on that?

**Comment by Wavesonics** [comment]
`Apache License 2.0` might be what you want then. It's essentially unlimited permissiveness with respect to usage and modification, but requires a notice be included somewhere that it's being used.

In the Android ecosystem essentially every open source library uses this one.

**Comment by Calinou** [comment]
@Wavesonics Both the MIT and Apache 2 licenses require including a copyright notice somewhere in the distribution, but neither of these licenses require you to make it prominent somehow. The only difference is that Apache 2 requires you to state any changes you've made to the software, unlike MIT.

**Comment by TheRektafire** [comment]
I think it should be MIT as well if for no other reason than most open source godot projects are MIT as well, so basically i agree with calinou

**Comment by donovan1212** [comment]
I Quite Like the MIT license, since you are the only contributor it is easy right now to switch.

**Comment by ShiftyAxel** [comment]
I've thought it over, and the MIT license seems like the way to go. Its simplicity and standardization in the Godot ecosystem are both appealing.

Plus, I'd prefer not to be That Guy and dig my heels in over demanding a mandatory credit if it means putting up barriers to Qodot's usage, particularly when most open-source folks operate on an honour basis anyway.

Thanks for the advice everyone, the license has been updated in the latest commit.

**Comment by donovan1212** [comment]
Got it!
