### ISSUE TITLE
"full build" is missing

### ISSUE THREAD

**Issue by Serasul1984** [ShiftyAxel/Qodot#171]
the button "Full Built" is missing in my Godot ?
i made this tutorial here: https://www.youtube.com/watch?v=dVagDDRb2jQ

**Comment by DeerTears** [comment]
This was solved in the official discord. If you're following the above tutorial, make sure you're using Godot 3.0. There is a Qodot available for Godot 4.0 with its own setup instructions: https://github.com/QodotPlugin/qodot/ The above tutorial won't work on Godot 4.0.
