### ISSUE TITLE
Fully modular QodotMap generation functionality

### ISSUE THREAD

**Issue by ShiftyAxel** [ShiftyAxel/Qodot#25]
All node-creation functionality within QodotMap should eventually be modular, to support a variety of rendering workflows.

Case in point from Arkii:
"I'd like to play with rendering it all as one draw call, without culling it might be fine even on decent modern hardware"

Right now that'd require directly inheriting from QodotMap and copy-pasting a ton of existing code around, which isn't a great way to extend. The geo generation stuff needs a refactor anyway since it's getting tall enough to tip over, so might as well do this at the same time.

**Comment by ShiftyAxel** [comment]
Other possibilities:
- QBSP-style subtractive modeling using CSG nodes
- Additive modeling using CSG nodes
- Implemetation-specific geo generation for optimal culling

**Comment by donovan1212** [comment]
Here might be a good thing to look at, it is the source code for Qutils, which includes QBSP if I am not mistaken, this should allow for understanding at what it does, It also includes VIS too, this stuff should allow for more understanding on what happens

**Comment by ShiftyAxel** [comment]
The groundwork for this has been laid by the recent QodotMap refactor, but the actual structural changes still need to be implemented.

It's more complex than originally envisioned since the various different methods of geometry generation (aggregating surfaces per-material, for example) would have to exist independently of a tree structure, but the tree structure is currently necessitated by entity spawning.

**Comment by ShiftyAxel** [comment]
Implemented in the texture-loader branch
