### ISSUE TITLE
Clearer documentation on the asset library / git master file difference & plugin update procedure

### ISSUE THREAD

**Issue by kakoeimon** [ShiftyAxel/Qodot#57]
I just downloaded 1.4 and 1.3 for windows and linux and in the zip file I found a Qodot executable.
As far I understand you do not even have to have separated OS downloads.
P.S. I tried to download master but for some reason the folders outside of the dir addon are not included and master requires them. If you need textures like the standard one in the plugin keep it in the addon dir.

Great job by the way, thanks.

**Comment by kakoeimon** [comment]
Looks like that I was wrong. The addon is in src download.

**Comment by ShiftyAxel** [comment]
Yeah, it's set up that way to keep the core addon light and make sure the asset library distribution isn't bloated with example content (scenes, textures, etc) that the user may not need.

I'll make this more clear in the documentation, and add a note about deleting the plugin before updating- a few users have been tripped up by that now.

**Comment by ShiftyAxel** [comment]
This is done:
https://github.com/ShiftyAxel/Qodot/wiki/Installation
