### ISSUE TITLE
Support full range of Quake map formats

### ISSUE THREAD

**Issue by ShiftyAxel** [ShiftyAxel/Qodot#6]
The first step toward supporting formats- need to save out the test geometry in each different map format, then run text diffs to compare them and determine how the formats are differentiated.

**Comment by Calinou** [comment]
Many Quake map authors prefer using the Valve map format nowadays, as it makes it possible to keep the original texture aspect on sloped surfaces. TrenchBroom supports both the standard and Valve map formats natively.

**Comment by ShiftyAxel** [comment]
I've done some initial testing by exporting the same geometry from TrenchBroom in each format:

- Brush geometry appears to import fine from all formats
- Texture UV, rotation and scale appears to import fine from all formats except Valve
- The Quake 2, Quake 3 and Daikatana formats add 3 extra optional integer parameters to the end of each plane's texture info
  - These are handled gracefully by QuakeMapReader, but are discarded during parse in the current code
  - Surface - Appears to be a bitmask for various game-specific parameters like fullbright, nodraw, metal, stone, glass, etc.
  - Content - Appears to be a bitmask for a second set of game-specific parameters like solid, window, lava, slime, water, etc.
  - Color - Unsure. It's a free text field in TrenchBroom, but outputs a number. Integer enum against known string color names?
- The Valve format swaps the two-part floating point UV offset for a four-part floating point array enclosed by square braces, ex: [ 0 0 1 0 ]
  - Unsure what these represent, but the middle two numbers appear to be similar to the x/y UV offset from the standard format?
  - The TrenchBroom editor doesn't expose any new fields for Valve format, so this must be something calculated implicitly from the plane data
  - Does the Valve format use a different method for inferring base UV coordinates? Is it still triplanar as per the standard format?
- One major difference between formats appears to be the default parameters available in the worldspawn entity's properties.
  - These are handled gracefully and largely immaterial to Qodot, but I need to double-check that the worldspawn can be customized based on its properties through the QuakeMapNode override interface.

@Calinou That lines up with my findings, and evidently has something to do with the extra data provided in each plane's UV section.

This is looking way more doable than I expected after my initial round of format research, so I'm upgrading this issue to an official 'support the other formats'.

**Comment by ShiftyAxel** [comment]
Reference documentation & code from Arkii on the TrenchBroom discord:

http://mattn.ufoai.org/files/MAPFiles.pdf

     var uvs = new Vector2();

            uvs.X  = Vector3.Dot(BrushPlane.TextureXAxis.Axis, Pos);
            uvs.X /= ((float)TexInfo.Width) / BrushPlane.TextureScale.X;
            uvs.X += BrushPlane.TextureXAxis.Offset / TexInfo.Width;

            uvs.Y = Vector3.Dot(BrushPlane.TextureYAxis.Axis, Pos);
            uvs.Y /= ((float)TexInfo.Height) / BrushPlane.TextureScale.Y;
            uvs.Y += BrushPlane.TextureYAxis.Offset / TexInfo.Height;

    return uvs;

**Comment by ShiftyAxel** [comment]
Fixed in the latest commits, will push out 1.2.0 soon.
