### ISSUE TITLE
Texture WAD support

### ISSUE THREAD

**Issue by ShiftyAxel** [ShiftyAxel/Qodot#7]
Most (if not all) existing Quake-format maps use WAD files instead of loose textures, so Qodot should support a texture import workflow at the very least, and full import/export if possible.

**Comment by ShiftyAxel** [comment]
Possible reference code:
https://github.com/WarrenMarshall/QuakeWADViewer/blob/master/src/main.py

**Comment by GoomiChan** [comment]
That python didn't seem to cover the format of the mip textures in the wad itself so I gisted my wad stuff incase its a help. https://gist.github.com/GoomiChan/3a8ecbff4992157ca55763bd6d56c5ff (or maybe I missed the loading after the entries in that script).

The bytes in the mip tex are indices into the palette (can grab here: https://quakewiki.org/wiki/Quake_palette)

Incase that helps :>

**Comment by ShiftyAxel** [comment]
I've implemented a palette.lmp importer that reads into a PoolColorArray and saves it as a resource file, for use during the WAD import process.

Next stop: Textures.

**Comment by ShiftyAxel** [comment]
I've implemented WAD importing and integrated with the texture loader in the latest commit.
